# 应用服务 WEB 访问端口
server:
  port: 8888

spring:
  datasource:
    username: root
    password: 123qwe
    url: jdbc:mysql:///craftmanspirit
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.ouwen: debug
